//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.SearchJobs = new HashSet<SearchJob>();
            this.TrackedFiles = new HashSet<TrackedFile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SearchJob> SearchJobs { get; set; }
        public virtual ICollection<TrackedFile> TrackedFiles { get; set; }
    }
}
