//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpdate
    {
        public int Id { get; set; }
        public System.DateTime Stamp { get; set; }
        public int TrackedFileId { get; set; }
    
        public virtual TrackedFile TrackedFile { get; set; }
    }
}
