//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Index
    {
        public Index()
        {
            this.Users = new HashSet<User>();
            this.TrackedFiles = new HashSet<TrackedFile>();
        }
    
        public int Id { get; set; }
        public string Alias { get; set; }
    
        public virtual TrackedFolder Root { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<TrackedFile> TrackedFiles { get; set; }
    }
}
