//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    
    public enum PdfVersion : int
    {
        v13 = 0,
        v14 = 1,
        v15 = 2,
        v16 = 3,
        v17 = 4
    }
}
