//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReductionLog
    {
        public int Id { get; set; }
        public long OldSize { get; set; }
        public long NewSize { get; set; }
    
        public virtual ShrinkJob ShrinkJob { get; set; }
        public virtual TrackedFile TrackedFile { get; set; }
    }
}
