//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    
    public enum SearchStatus : int
    {
        Pending = 0,
        Running = 1,
        Paused = 2,
        Cancelled = 3,
        Rejected = 4,
        Completed = 5
    }
}
