//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Indices = new HashSet<Index>();
            this.WorkingSets = new HashSet<WorkingSet>();
            this.ShrinkJobs = new HashSet<ShrinkJob>();
            this.SearchJobs = new HashSet<SearchJob>();
            this.RegExTemplates = new HashSet<RegExTemplate>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Salt { get; set; }
        public string Hash { get; set; }
        public string Login { get; set; }
        public bool IsSysAdmin { get; set; }
        public bool NewPasswordDue { get; set; }
    
        public virtual ICollection<Index> Indices { get; set; }
        public virtual ICollection<WorkingSet> WorkingSets { get; set; }
        public virtual ICollection<ShrinkJob> ShrinkJobs { get; set; }
        public virtual ICollection<SearchJob> SearchJobs { get; set; }
        public virtual ICollection<RegExTemplate> RegExTemplates { get; set; }
    }
}
